---
ID: "fca86d2e-711d-4727-a4dc-352ca34847db"
Parent: "1b70d039-4484-4c72-849f-ae027d72638a"
Template: "1b70d039-4484-4c72-849f-ae027d72638a"
Path: /sitecore/templates/Foundation/AIServices/AIServicesSettings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240302T080741Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "56cf7e27-0bf8-42d3-a8c2-4b052f66fb6f"
      Hint: NumberOfChoices
      Value: 1
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0e719dc2-265a-4101-b78d-99c37d6f0b64"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240302T165658Z
